name: 'Start chain'
description: 'Action to start a desmos chain'
inputs:
  version:
    description: 'Binary version to be used when starting the chain'
    required: true

  genesis-file:
    description: 'Path to the genesis file that should be used to start the chain'
    required: false
    default: ''

  pre-run:
    description: 'Script to be executed before the chain starts'
    required: false
    default: ''

  post-run:
    description: 'Script to be executed after the chain has started'
    required: false
    default: ''

outputs:
  desmos-bin:
    description: "Desmos binary path"
    value: ${{ steps.start-chain.outputs.desmos-bin }}
  desmos-home:
    description: "Desmos home path"
    value: ${{ steps.start-chain.outputs.desmos-home }}

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - id: start-chain
      run: CI=true start-chain.sh -v ${{ inputs.version }} -g "${{ inputs.genesis-file }}" -p "${{ inputs.pre-run }}" -P "${{ inputs.post-run }}" >> $GITHUB_OUTPUT
      shell: bash
