on:
  push:
    branches:
      - manuel/DCD-121/start-chain-action

jobs:
  test_chain_start:
    runs-on: ubuntu-latest
    name: Test chain start
    steps:
      - name: Start chain
        uses: desmos-labs/start-chain@v1
        with:
          version: v4.4.1

      - run: ./desmos q block
        shell: bash
