on:
  push:
    branches:
      - manuel/DCD-121/start-chain-action

jobs:
  test_chain_start:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Start chain
        uses: desmos-labs/start-chain@v1
        with:
          version: v4.4.1

      - run: ls -al
        shell: bash
